version: 2
jobs:
  build:
  working-directory: ~/playground
  docker:
    - image: circleci/node:10.14.2
  steps:
    - checkout
    - run:
      name: install-dependencies
      command: 'npm install'