version: 2
jobs:
  build:
    working-directory: ~/playground
    steps:
      - run:
          name: "Build with docker"
          command: "docker build -t latest ."
      - run:
          name: "Push docker image"
          command: "docker push rosepollock/playground:latest"