version: 2
jobs:
  build:
    working-directory: ~/playground
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build with docker"
          command: "docker build -t rosepollock/playground ."
      - run:
          name: "Push docker image"
          command: "docker push rosepollock/playground:latest"