version: 2
jobs:
  build:
    working-directory: ~/playground
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build with docker"
          command: "docker build -t rosepollock/playground ."
      - deploy:
          name: "Push docker image"
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID $DOCKER_HUB_PWD
            docker push rosepollock/playground:latest